# Generated by Django 5.2.6 on 2026-02-20 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0018_add_review_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThisDayInHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The date (month and day matter, year is stored separately)"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "year",
                    models.IntegerField(
                        blank=True, help_text="The year this event occurred", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "This Day in History",
                "verbose_name_plural": "This Day in History",
                "ordering": ["year"],
            },
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="music_review_user_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="review",
            name="music_review_album_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="reviewlike",
            name="music_reviewlike_review_created_idx",
        ),
        migrations.AddIndex(
            model_name="thisdayinhistory",
            index=models.Index(fields=["date"], name="music_thisd_date_345da9_idx"),
        ),
    ]
